
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VPaned vpaned1;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Entry roomName;
	
	private global::Gtk.Entry Stage;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Entry input;
	
	private global::Gtk.Button submitButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 252;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 10;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Room Name:");
		this.hbox3.Add (this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.roomName = new global::Gtk.Entry ();
		this.roomName.CanFocus = true;
		this.roomName.Name = "roomName";
		this.roomName.IsEditable = false;
		this.roomName.InvisibleChar = '•';
		this.hbox3.Add (this.roomName);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.roomName]));
		w2.Position = 1;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Stage = new global::Gtk.Entry ();
		this.Stage.HeightRequest = 230;
		this.Stage.CanFocus = true;
		this.Stage.Name = "Stage";
		this.Stage.IsEditable = false;
		this.Stage.InvisibleChar = '•';
		this.vbox1.Add (this.Stage);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Stage]));
		w4.Position = 1;
		this.hpaned1.Add (this.vbox1);
		this.vpaned1.Add (this.hpaned1);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.hpaned1]));
		w6.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.input = new global::Gtk.Entry ();
		this.input.CanFocus = true;
		this.input.Name = "input";
		this.input.IsEditable = true;
		this.input.InvisibleChar = '•';
		this.hbox5.Add (this.input);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.input]));
		w7.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.submitButton = new global::Gtk.Button ();
		this.submitButton.CanFocus = true;
		this.submitButton.Name = "submitButton";
		this.submitButton.UseUnderline = true;
		this.submitButton.Label = global::Mono.Unix.Catalog.GetString ("Submit");
		this.hbox5.Add (this.submitButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.submitButton]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.vpaned1.Add (this.hbox5);
		this.Add (this.vpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 417;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.submitButton.Clicked += new global::System.EventHandler (this.OnSubmitButtonClicked);
	}
}
