
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table4;
	
	private global::Gtk.Button button20;
	
	private global::Gtk.Button button21;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Entry num1;
	
	private global::Gtk.Entry num2;
	
	private global::Gtk.VBox vbox8;
	
	private global::Gtk.Button button23;
	
	private global::Gtk.Button button24;
	
	private global::Gtk.VBox vbox9;
	
	private global::Gtk.Button button26;
	
	private global::Gtk.Entry result;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.button20 = new global::Gtk.Button ();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.table4.Add (this.button20);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table4 [this.button20]));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.button21 = new global::Gtk.Button ();
		this.button21.CanFocus = true;
		this.button21.Name = "button21";
		this.button21.UseUnderline = true;
		this.button21.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.table4.Add (this.button21);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table4 [this.button21]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Input 1");
		this.table4.Add (this.label4);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table4 [this.label4]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Input 2");
		this.table4.Add (this.label5);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table4 [this.label5]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Result");
		this.table4.Add (this.label6);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table4 [this.label6]));
		w5.TopAttach = ((uint)(2));
		w5.BottomAttach = ((uint)(3));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.num1 = new global::Gtk.Entry ();
		this.num1.CanFocus = true;
		this.num1.Name = "num1";
		this.num1.IsEditable = true;
		this.table4.Add (this.num1);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table4 [this.num1]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.num2 = new global::Gtk.Entry ();
		this.num2.CanFocus = true;
		this.num2.Name = "num2";
		this.num2.IsEditable = true;
		this.table4.Add (this.num2);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table4 [this.num2]));
		w7.TopAttach = ((uint)(1));
		w7.BottomAttach = ((uint)(2));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.button23 = new global::Gtk.Button ();
		this.button23.CanFocus = true;
		this.button23.Name = "button23";
		this.button23.UseUnderline = true;
		this.button23.Label = global::Mono.Unix.Catalog.GetString ("x");
		this.vbox8.Add (this.button23);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.button23]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.button24 = new global::Gtk.Button ();
		this.button24.CanFocus = true;
		this.button24.Name = "button24";
		this.button24.UseUnderline = true;
		this.button24.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.vbox8.Add (this.button24);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.button24]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.table4.Add (this.vbox8);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table4 [this.vbox8]));
		w10.TopAttach = ((uint)(2));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.button26 = new global::Gtk.Button ();
		this.button26.CanFocus = true;
		this.button26.Name = "button26";
		this.button26.UseUnderline = true;
		this.button26.Label = global::Mono.Unix.Catalog.GetString ("Clear");
		this.vbox9.Add (this.button26);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.button26]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.result = new global::Gtk.Entry ();
		this.result.CanFocus = true;
		this.result.Name = "result";
		this.result.IsEditable = false;
		this.vbox9.Add (this.result);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.result]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.table4.Add (this.vbox9);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table4 [this.vbox9]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.table4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 622;
		this.DefaultHeight = 525;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button26.Clicked += new global::System.EventHandler (this.OnButton26Clicked);
		this.button23.Clicked += new global::System.EventHandler (this.OnButton23Clicked);
		this.button24.Clicked += new global::System.EventHandler (this.OnButton24Clicked);
		this.button21.Clicked += new global::System.EventHandler (this.OnButton21Clicked);
		this.button20.Clicked += new global::System.EventHandler (this.OnButton20Clicked);
	}
}
